services:
  db:
    image: postgres
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - 5436:5432
    volumes:
      - ./postgres_data:/var/lib/mysql